# ------------------------------------------------------------------------------
#
#   Copyright 2023
#   Copyright 2023 valory-xyz
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# ------------------------------------------------------------------------------

"""This package contains a behaviour that autogenerated from the protocol ``."""

import os
from abc import ABC
from enum import Enum
from typing import Any

from aea.skills.behaviours import State, FSMBehaviour


class Optimism0abciappEvents(Enum):
    """Events for the fsm."""

    RETRY_LIMIT_REACHED = "RETRY_LIMIT_REACHED"
    DONE = "DONE"
    ERROR = "ERROR"
    RETRY = "RETRY"


class Optimism0abciappStates(Enum):
    """States for the fsm."""

    VERIFICATIONROUND = "verificationround"
    RETRYLIMITROUND = "retrylimitround"
    MAXTIMEOUTSREACHEDROUND = "maxtimeoutsreachedround"
    CIRCUITBREAKERROUND = "circuitbreakerround"


class BaseState(State, ABC):
    """Base class for states."""

    _state: Optimism0abciappStates = None

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._event = None
        self._is_done = False  # Initially, the state is not done

    def act(self) -> None:
        """Perform the act."""
        self._is_done = True
        self._event = Optimism0abciappEvents.DONE

    def is_done(self) -> bool:
        """Is done."""
        return self._is_done

    @property
    def event(self) -> str | None:
        """Current event."""
        return self._event


# Define states


class VerificationRound(BaseState):
    """This class implements the behaviour of the state VerificationRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Optimism0abciappStates.VERIFICATIONROUND


class RetryLimitRound(BaseState):
    """This class implements the behaviour of the state RetryLimitRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Optimism0abciappStates.RETRYLIMITROUND


class MaxTimeoutsReachedRound(BaseState):
    """This class implements the behaviour of the state MaxTimeoutsReachedRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Optimism0abciappStates.MAXTIMEOUTSREACHEDROUND


class CircuitBreakerRound(BaseState):
    """This class implements the behaviour of the state CircuitBreakerRound."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state = Optimism0abciappStates.CIRCUITBREAKERROUND


class Optimism0abciappFsmBehaviour(FSMBehaviour):
    """This class implements a simple Finite State Machine behaviour."""

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.register_state(
            Optimism0abciappStates.MAXTIMEOUTSREACHEDROUND.value, MaxTimeoutsReachedRound(**kwargs), True
        )

        self.register_state(Optimism0abciappStates.VERIFICATIONROUND.value, VerificationRound(**kwargs))
        self.register_state(Optimism0abciappStates.RETRYLIMITROUND.value, RetryLimitRound(**kwargs))
        self.register_state(Optimism0abciappStates.CIRCUITBREAKERROUND.value, CircuitBreakerRound(**kwargs))

        self.register_transition(
            source=Optimism0abciappStates.CIRCUITBREAKERROUND.value,
            event=Optimism0abciappEvents.ERROR,
            destination=Optimism0abciappStates.MAXTIMEOUTSREACHEDROUND.value,
        )
        self.register_transition(
            source=Optimism0abciappStates.MAXTIMEOUTSREACHEDROUND.value,
            event=Optimism0abciappEvents.RETRY,
            destination=Optimism0abciappStates.VERIFICATIONROUND.value,
        )
        self.register_transition(
            source=Optimism0abciappStates.RETRYLIMITROUND.value,
            event=Optimism0abciappEvents.DONE,
            destination=Optimism0abciappStates.CIRCUITBREAKERROUND.value,
        )
        self.register_transition(
            source=Optimism0abciappStates.RETRYLIMITROUND.value,
            event=Optimism0abciappEvents.ERROR,
            destination=Optimism0abciappStates.MAXTIMEOUTSREACHEDROUND.value,
        )
        self.register_transition(
            source=Optimism0abciappStates.VERIFICATIONROUND.value,
            event=Optimism0abciappEvents.DONE,
            destination=Optimism0abciappStates.CIRCUITBREAKERROUND.value,
        )
        self.register_transition(
            source=Optimism0abciappStates.VERIFICATIONROUND.value,
            event=Optimism0abciappEvents.ERROR,
            destination=Optimism0abciappStates.MAXTIMEOUTSREACHEDROUND.value,
        )
        self.register_transition(
            source=Optimism0abciappStates.VERIFICATIONROUND.value,
            event=Optimism0abciappEvents.RETRY_LIMIT_REACHED,
            destination=Optimism0abciappStates.RETRYLIMITROUND.value,
        )

    def setup(self) -> None:
        """Implement the setup."""
        self.context.logger.info("Setting up Optimism0abciapp FSM behaviour.")

    def teardown(self) -> None:
        """Implement the teardown."""
        self.context.logger.info("Tearing down Optimism0abciapp FSM behaviour.")

    def act(self) -> None:
        """Implement the act."""
        super().act()
        if self.current is None:
            self.context.logger.info("No state to act on.")
            self.terminate()

    def terminate(self) -> None:
        """Implement the termination."""
        os._exit(0)
